import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import FriendsPage from './components/FriendsPage'
import Navbar from './components/Navbar'
import styled from "styled-components";
import FriendsData from "./data/FriendsData"

const inter = Inter({ subsets: ['latin'] })

const StyledContainer = styled.body`
display: flex;
justify-content: flex-start;
  background-color: yellow;
  overflow: hidden;
    height: 100vh;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Clerkie Friends Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <main >
          <StyledContainer>
            <Navbar/>
            <FriendsPage data={FriendsData}/>
          </StyledContainer>
        </main>
      </body>
      
    </>
  )
}
